### ISSUE TITLE
Add Mozilla push staging server to whitelist

### ISSUE THREAD

**Issue by ncalexan** [beverloo/peter.sh#14]
I see you have the Mozilla push production server at https://github.com/beverloo/peter.sh/blob/78e464879436de0f0a8520adef01d82868402e9f/tests/push.php#L22.  Could you add https://updates-autopush.stage.mozaws.net?  It'll ease testing new clients, like the Firefox for Android implementation I'm working on.

Thanks for a great testing resource!

/cc @jrconlin @bbangert

**Comment by beverloo** [comment]
Absolutely, fixed in 87bc346.

Please let me know if anything in particular will be useful for your testing. I plan to redo parts of the push generator to include more granular failures in payloads, VAPID and so on.
